### ISSUE TITLE
Padding problem in online HTML version

### ISSUE THREAD

**Issue by zigarn** [progit/progit2#175]
In the online HTML version, the code block have padding for each sub-element which has a not nice display with space around every piece of code:
![code_padding](https://cloud.githubusercontent.com/assets/175128/5043861/6d672a1a-6bea-11e4-8095-444c1848f557.png)

The problem is the `padding: 3px` for the rule `.edition2 code` as each piece of code block is in a `<code>` element with specific class for syntax coloration.

``` css
/* line 488, /Users/schacon/github/progit/gitscm2/app/assets/stylesheets/book2.css.scss */
.edition2 code, .edition2 .man-page p tt, .man-page p .edition2 tt, .edition2 .man-page .listingblock .content, .man-page .listingblock .edition2 .content {
  /* inline code */
  border: 1px solid #f5f5f5;
  padding: 3px;
  background: #eee;
  color: #333;
}
```

With a `padding: 0px`, it looks much nicer:
![code_padding_0](https://cloud.githubusercontent.com/assets/175128/5043882/c4494ab6-6bea-11e4-8b67-b2a0214efd10.png)

No problem in the ePub nor PDF versions.
